name: deploy_to_server #Name of the Workflow

on: #Name of the GitHub event that triggers the workflow
  push: #On Push Event We need to take action
    branches: #Now we need to specify the branch name
      - main

jobs: #Workflow run is made up of one or more jobs
  deploy:
    env:
      TASK_ID: ''
    runs-on: ubuntu-latest #Through which Server OS we need to Work (type of machine to run the job on)
    steps:
      #Using versioned actions
      - name: Checkout
        uses: actions/checkout@v2 # --> Reference a specific version

      - uses: actions/setup-node@v2 # --> To Setup the Server With Node Env
        with:
          node-version: '16' #--> Specify the Version of the Node

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1 #--> Setup the Credential for the AWS cli
        with:
          # Created the Secrets Under the Repo only with These Variables
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 #--> Define Region of the AWS-CLI

      - name: Add .env file
        run: |
          printf "\nMONGO_URI=${{ secrets.MONGO_URI }}" >> server/.env
          printf "\nLIVEDATA_INTERVAL=${{ secrets.LIVEDATA_INTERVAL }}" >> server/.env

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get running task
        id: get_task_id
        run: |
          echo `aws sts get-caller-identity`
          echo "taskID=`aws ecs list-tasks --cluster myCluster --desired-status RUNNING | egrep "task" | tr "/" " " |  awk '{print $4}' | tr -d '\n'`" >> $GITHUB_ENV
          echo "TASK_ID=${{ env.taskID }}"
          echo "TASK_ID='${{ env.taskID }}'"
          echo "action_state=yellow" >> $GITHUB_ENV

      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
          echo "TASK_ID=${{ env.taskID }}"

      - name: Kill ecs task
        if: ${{ env.taskID }}
        run: |
          aws ecs stop-task --cluster myCluster --task "${{ env.taskID }}" --reason "redeploy"

      - name: Add buildx plugin for docker
        id: add-buildx
        run: |
          wget https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64
          mkdir -p ~/.docker/cli-plugins/
          mv buildx-v0.8.2.linux-amd64 ~/.docker/cli-plugins/docker-buildx
          chmod +x ~/.docker/cli-plugins/docker-buildx

      - name: Build, tag, and push to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cryptojs-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --platform linux/amd64,linux/arm64 --name myarch
          docker buildx use myarch
          docker buildx build --platform linux/amd64,linux/arm64 -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" --push server
          printf "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Fill in the new image ID in the ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: server/task_definition.json
          container-name: cryptojs-container
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: cryptojs-service
          cluster: myCluster
          wait-for-service-stability: true
